# Week 2 #

**Question 1**
List three different real networks and state the nodes and links for each of them.

**WWW**
Webpages are nodes, links are edges.

**Social Network**
People are nodes, relationships are edges.

**GPS maps**
Street intersections are nodes,streets are edges.


**Question 2**
Tell us of the network you are personally most interested in. Address the following questions:

* What are its nodes and links?
* How large is it?
* Can be mapped out?
* Why do you care about it?

I find the human interconnectivity very insteresting. The six-degree of bacon theory seems very curious, the idea that we are all interconnected by just a couple of links.
Every human is a node and links are events or realtionships which connect these people.
It has about 7.3 Billion nodes, the number of links varies by what you define as having a connection or relationship to another person, but it's a huge amount.
Not easily, it again depends on definitions of when humans are connected, how intimit does the relation have to be to consider them connected. Facebook is kinda atempting this, with a very narrow definition of relation.
I think it shows how closly connected we all are and how similiar.

**Question 3** In your view what would be the area where network science could have the biggest impact in the next decade? Explain your answer - and base it on the text in the book.

The book explains how networks are underlying almost every complex system we know to date. With human evolution our systems are just getting more and more complex, with more layers and more individually moving parts. Systems have been getting to complex to understand at a glance and network analysis is the biggest step to automating a lot of complex system designing. As such I think network science biggest impact might just be it becoming part of every other science (as it already has). So while it might lead to some major break throughs in Computer Science, Social Science, Biology or Chemistry, I believe the most important part of network science is how it can be applied to everything else. How it already plays a roll in day-to-day live for millions in the form of GPS and improving productivity in a lot of aspects of our society. 
I see network science as a tool to improve thousands of different areas, as these are improved they get more efficent which will solve many problems, which we are currently facing. 


**Question 4**
Section 2.5 states that real networks are sparse. Can you think of a real network where each node has many connections? Is that network still sparse? If yes, can you explain why?

I can come up with many, non-spares and even many complete networks, where every note is connected with every other note, but most of these are useless. If every node is connected with every other node, then there is no reason to model the dependency (unless the nodes are weighted or directed). It all depends on the requirments for a node to be linked to another node. If for example we had a network showing the relations of students in a class, the studends are the nodes. If we say that two nodes are linked if the students are friends, then we would get a *normal* spares network, but if we were to say that two nodes are linked if the students simply know each other, we would end up with a complete network. The latter network would be useless, since it's implied that everyone in the class at least knows each other, or has seen each other. As such there are *real* networks which aren't sparse, but we are rarely interessted in these. If there is an overabundance of connections, then there is rarely a reason to analyse the network at all, unless we wish to discover which nodes **aren't** linked, in which case we should reverse our network parameters and ask which students do not know each other, just as an example. Interestingly this means that networks can also be used to model the lack of connectivity.

## Working with networkx ##

In [2]:
import networkx as nx
G=nx.Graph()
G.add_node(1)
G.add_nodes_from([2,3])

In [3]:
G.add_edge(1,2)
e=(2,3)
G.add_edge(*e)
G.add_edge(3,1)

In [4]:
G.nodes()

[1, 2, 3]

In [5]:
G.edges()

[(1, 2), (1, 3), (2, 3)]

In [6]:
G.neighbors(2)

[1, 3]

In [7]:
import matplotlib.pyplot as plt

nx.draw(G)
plt.show()

## Book Excercises ##

**2.1. Königsberg Problem**
Which of the icons in Figure 2.19 can be drawn without raising your
pencil from the paper, and without drawing any line more than once?
Why?

**A**
This one does fulfill the requirements, since it has only two nodes with an uneven number of edges.

**B**
This one does **not** fulfill the requirments, since it has neither two nor zero nodes with an uneven number of edges, it has 4.

**C**
This one has 12 nodes, which all have either 2 or 4 edges, which means there are zero nodes with an uneven number of edges, which means it fulfills the requirments.

**D**
If we consider the highest and lowest points of the two elipses as nodes, we can see that all nodes that are part of the main figure have an even number of edges with the exception of the one node in the bottom right, which only has one edge. Meaning that the requirments are not fulfilled, since there is one and only one node with an uneven number of edges.



**2.3. Graph Representation**
The adjacency matrix is a useful graph representation for many analytical
calculations. However, when we need to store a network in a computer,
we can save computer memory by offering the list of links in a Lx2 matrix,
whose rows contain the starting and end point i and j of each link.

**(a) The corresponding adjacency matrices**

In [8]:
import numpy
one = numpy.matrix('0 1 1 1 0 1; 1 0 1 1 0 0; 1 1 0 0 0 1; 1 1 0 0 0 0; 0 0 0 0 0 0; 1 0 1 0 0 0')

print "One: "
print one

two = numpy.matrix('0 1 0 0 0 0; 0 0 1 1 0 0; 1 1 0 0 0 0; 1 0 0 0 0 0; 0 0 0 0 0 0; 1 0 1 0 0 0')

print "Two: "
print two

One: 
[[0 1 1 1 0 1]
 [1 0 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
Two: 
[[0 1 0 0 0 0]
 [0 0 1 1 0 0]
 [1 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]


**(b) The corresponding link lists.**

In [9]:


one = numpy.matrix('1 2; 1 3; 1 4; 1 6; 2 3; 2 4; 3 6')
two = numpy.matrix('1 2; 3 1; 4 1; 6 1; 2 3; 3 2; 2 4; 6 3')

print "One: "
print one
print "Two: "
print two


One: 
[[1 2]
 [1 3]
 [1 4]
 [1 6]
 [2 3]
 [2 4]
 [3 6]]
Two: 
[[1 2]
 [3 1]
 [4 1]
 [6 1]
 [2 3]
 [3 2]
 [2 4]
 [6 3]]


**(c) Determine the average clustering coefficient of the network
shown in Figure 2.20a.**

In [10]:
from decimal import *
getcontext().prec = 6
L = Decimal(7) 

N = Decimal(6)

k_all = 2*L/N

print k_all


2.33333


**(d) If you switch the labels of nodes 5 and 6 in Figure 2.20a, how does
that move change the adjacency matrix? And the link list?**

In [11]:
adjacency = numpy.matrix('0 1 1 1 0 1; 1 0 1 1 0 0; 1 1 0 0 0 1; 1 1 0 0 0 0; 1 0 1 0 0 0; 0 0 0 0 0 0')
link = numpy.matrix('1 2; 1 3; 1 4; 1 5; 2 3; 2 4; 3 5')

print "Adjacency"
print adjacency
print "Link"
print link


Adjacency
[[0 1 1 1 0 1]
 [1 0 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 0 0]
 [1 0 1 0 0 0]
 [0 0 0 0 0 0]]
Link
[[1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 3]
 [2 4]
 [3 5]]


**(e) What kind of information can you not infer from the link list
representation of the network that you can infer from the adjacency
matrix?**

Whether or not there are completly unconnected notes

**(f) In the (a) network, how many paths (with possible repetition of
nodes and links) of length 3 exist starting from node 1 and ending
at node 3? And in (b)?**

(a) = 6
(b) = 0


**(g) With the help of a computer, count the number of cycles of
length 4 in both networks.**

## Ploting ##

In [12]:
import random as rand

random_array = numpy.random.normal(2,0.125,5000)

histo = numpy.histogram(random_array, bins=10)



In [13]:

array = numpy.ones(histo[0].size)

for num in range(0,histo[1].size-1):
    array[num]=histo[1][num]+((histo[1][num+1]-histo[1][num])/2)

plt.plot(array,histo[0])
plt.show()

In [82]:
random_pois = numpy.random.poisson(10,5000)

random_pois.sort()

print "min: "
print random_pois[0]
print "max "
print random_pois[random_pois.size-1]


min: 
0
max 
22


In [83]:
pois_array = numpy.ones(random_pois[random_pois.size-1]-random_pois[0] + 2)

print pois_array.size

pois_index = 0

for num in range(random_pois[0],random_pois[random_pois.size-1]+2):
    pois_array[pois_index] = num
    pois_index = pois_index + 1
    
print pois_array




24
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.]


In [84]:
print random_pois
pois_histo = numpy.histogram(random_pois, pois_array)
print pois_histo


[ 0  1  1 ..., 22 22 22]
(array([  1,   3,  12,  32,  95, 184, 333, 446, 536, 602, 610, 613, 467,
       377, 264, 176, 114,  68,  28,  19,  12,   2,   6]), array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.]))


In [14]:
temp_array = numpy.ones(pois_histo[1].size-1)

for num in range(0,temp_array.size):
    temp_array[num] = pois_histo[1][num] 
    

bar = plt.bar(temp_array, pois_histo[0])
plt.show()

NameError: name 'pois_histo' is not defined